name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: "pre-commit"

  verify-apps:
    name: Build apps
    needs: pre-commit
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: macos-latest
      framework: ${{ matrix.framework }}
      target-platform: macOS
      target-format: app
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12-dev" ]
        framework: [ "toga", "pyside2", "pyside6", "ppb", "pygame" ]
        exclude:
          # PySide2 doesn't publish a binary wheel that is compatible
          # with Python 3.11+, and is unlikely to ever do so.
          - python-version: "3.11"
            framework: "pyside2"
          - python-version: "3.12-dev"
            framework: "pyside2"
          # PySide6 hasn't published a binary wheel that is compatible
          # with Python 3.12 yet.
          - python-version: "3.12-dev"
            framework: "pyside6"
          # Pygame hasn't published a binary wheel that is compatible
          # with Python 3.12 yet.
          - python-version: "3.12-dev"
            framework: "pygame"
